---
title: "More signatures in the dimmer staining sections"
format: html
---

```{r}
StorageLocation <- file.path("Figures", "Figure_DifferentBrightnessGateSamplings")
```

Load required packages via library call

```{r}
library(dplyr)
library(stringr)
library(purrr)
library(ggplot2)
library(flowCore)
library(flowWorkspace)
library(Luciernaga)
```

```{r}
Location <- file.path("/home", "david", "Desktop", "BUV496")

files <- list.files(Location, pattern="fcs", full.names=TRUE)
```

```{r}
StringRemoval <- c("CD8BUV496_", ".fcs")

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1), normalize=FALSE)

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("BUV496RawSignatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1))

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("BUV496Signatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)
```

```{r}
Brightnesses <- Luciernaga_FolderBrightness(FolderPath=Location, 
    sample.name="GUID", StringRemoval=StringRemoval,
    fluorophore.name="BUV496", detector="UV7-A",
    Verbose=TRUE, PanelCuts=c(0.5,1), legend="none",
    returnType="plot", maxtik=1e6)

FileName <- paste0("BUV496", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, Brightnesses, dpi = 600, width = 4, height = 3)
```

```{r}
print("Goodbye")
```

# BUV615

```{r}
Location <- file.path("/home", "david", "Desktop", "Data_SCs", "BUV615")

files <- list.files(Location, pattern="fcs", full.names=TRUE)
```

```{r}
StringRemoval <- c("CCR4BUV615_", ".fcs")

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1), normalize=FALSE)

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("BUV615RawSignatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1))

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("BUV615Signatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)
```

```{r}
Brightnesses <- Luciernaga_FolderBrightness(FolderPath=Location, 
    sample.name="GUID", StringRemoval=StringRemoval,
    fluorophore.name="BUV615", detector="UV10-A",
    Verbose=TRUE, PanelCuts=c(0.5,1), legend="none",
    returnType="plot", maxtik=1e6)

FileName <- paste0("BUV615", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, Brightnesses, dpi = 600, width = 4, height = 3)
```

```{r}
print("Goodbye")
```

# BUV615

```{r}
Location <- file.path("/home", "david", "Desktop", "Data_SCs", "BV650")

files <- list.files(Location, pattern="fcs", full.names=TRUE)
```

```{r}
StringRemoval <- c("CCR7BV650_", ".fcs")

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1), normalize=FALSE)

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("BV650RawSignatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1))

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("BV650Signatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)
```

```{r}
Brightnesses <- Luciernaga_FolderBrightness(FolderPath=Location, 
    sample.name="GUID", StringRemoval=StringRemoval,
    fluorophore.name="BV650", detector="V11-A",
    Verbose=TRUE, PanelCuts=c(0.5,1), legend="none",
    returnType="plot", maxtik=1e6)

FileName <- paste0("BV650", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, Brightnesses, dpi = 600, width = 4, height = 3)
```

```{r}
print("Goodbye")
```


# BV750

```{r}
Location <- file.path("/home", "david", "Desktop", "Data_SCs", "BV750")

files <- list.files(Location, pattern="fcs", full.names=TRUE)
```

```{r}
StringRemoval <- c("IFNgBV750_", ".fcs")

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1), normalize=FALSE)

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("BV750RawSignatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1))

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("BV750Signatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)
```

```{r}
Brightnesses <- Luciernaga_FolderBrightness(FolderPath=Location, 
    sample.name="GUID", StringRemoval=StringRemoval,
    fluorophore.name="BV750", detector="V15-A",
    Verbose=TRUE, PanelCuts=c(0.5,1), legend="none",
    returnType="plot", maxtik=1e6)

FileName <- paste0("BV750", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, Brightnesses, dpi = 600, width = 4, height = 3)
```

```{r}
print("Goodbye")
```

