---
title: "APC-Fire 810 Experiment #12"
format: html
---

```{r}
StorageLocation <- file.path("Figures", "Figures_TandemDegradation")
```

Load required packages via library call

```{r}
library(dplyr)
library(stringr)
library(purrr)
library(ggplot2)
library(flowCore)
library(flowWorkspace)
library(Luciernaga)
```

```{r}
Location <- file.path("/home", "david", "Desktop", "DegradedFluorophore")

files <- list.files(Location, pattern="fcs", full.names=TRUE)
```

```{r}
StringRemoval <- c("CD38APCFire810_", ".fcs")

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1), normalize=FALSE)

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("DegradingAPCFire810RawSignatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1))

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("DegradingAPCFire810Signatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)
```

```{r}
Brightnesses <- Luciernaga_FolderBrightness(FolderPath=Location, sample.name="GUID", StringRemoval=StringRemoval, fluorophore.name="", Verbose=TRUE, PanelCuts=c(0.5,1))

colnames(Brightnesses)
nrow(Brightnesses)
```

